- name: Installing and configuring cart
  hosts: cart
  become: yes
  tasks:
     - name: Disable nodejs current module
       ansible.builtin.shell: dnf module disable nodejs -y
     - name: "Enabling nodejs:18 version"
       ansible.builtin.shell: dnf module enable nodejs:18 -y
     - name: Installing nodejs
       ansible.builtin.package:
         name: nodejs
         state: latest
     - name: Adding user robosop
       ansible.builtin.user: 
         name: roboshop
     - name: "Creating /app directory"
       ansible.builtin.file:
         path: /app
         state: directory
     - name: Downloading application code
       ansible.builtin.get_url: 
          url: https://roboshop-builds.s3.amazonaws.com/cart.zip
          dest: /tmp/cart.zip
     - name: Extrarting application code
       ansible.builtin.unarchive:
         src: /tmp/cart.zip
         dest: /app
         remote_src: yes
     - name: Installing nodejs dependencies
       ansible.builtin.shell: npm install 
       args:
         chdir: /app
     - name: Copying cart.service file
       ansible.builtin.copy:
         src: /home/centos/Projectwork/Ansible/cart.service
         dest: /etc/systemd/system/cart.service
     - name: Reloading systemd service
       ansible.builtin.systemd_service: 
          daemon_reload: true
     - name: Enabling cart service 
       ansible.builtin.service:
          name: cart
          enabled: yes
     - name: Starting cart service
       ansible.builtin.service:
         name: cart
         state: started