- name: Check return code
  hosts: web
  become: yes
  tasks:
     - name: create a file
       ansible.builtin.file:
         path: /tmp/dinesh
         state: touch
       register: output
     - name: Printing output
       ansible.builtin.debug: 
        var: output
     - ansible.builtin.debug:
        msg: "Hello I am dinesh"
       when: output.failed == true