- name: Check return code
  hosts: web
  become: yes
  tasks:
     - name: create a file
       ansible.builtin.file:
         path: /tmp/dinesh
         state: touch
       register: output
     - name: Printing output
       ansible.builtin.debug: 
        var: output
     - ansible.builtin.debug:
        msg: "Hello I am dinesh"
       when: output.failed == true
     - name: checking if a file exists or not
       ansible.builtin.stat:
         path: /tmp/paddu
       register: paddu 
     - name: printing output
       ansible.builtin.debug: 
         var: paddu 
     - name: creating a file 
       ansible.builtin.file:
         path: /tmp/paddu
         state: touch
       when: paddu.stat.exists == false
        
