- name: Check return code
  hosts: web
  become: yes
  tasks:
     - name: create a file
       ansible.builtin.file:
         path: /tmp/dinesh
         state: file
       register: output
     - name: Printing output
       ansible.builtin.debug: 
         - var: output