- name: configuring catalogue server
  hosts: catalogue
  become: yes
  tasks:
    - name: Disable nodejs current module
      ansible.builtin.shell: dnf module disable nodejs -y
    - name: "Enabling nodejs:18 version"
      ansible.builtin.shell: dnf module enable nodejs:18 -y
    - name: Installing nodejs
      ansible.builtin.package:
        name: nodejs
        state: latest
    - name: Adding user robosop
      ansible.builtin.user: 
        name: roboshop
    - name: "Creating /app directory"
      ansible.builtin.file:
        path: /app
        state: directory
    - name: Downloading application code
      ansible.builtin.get_url: 
         url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
         dest: /tmp/catalogue.zip
    - name: Extrarting application code
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes
    - name: Installing nodejs dependencies
      ansible.builtin.shell: npm install 
      args:
        chdir: /app
    - name: Copying catalogue.service file
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service
    - name: Reloading systemd service
      ansible.builtin.systemd_service: 
         daemon_reload: true
    - name: Enabling catalogue service 
      ansible.builtin.service:
         name: catalogue
         enabled: yes
    - name: Starting catalogue service
      ansible.builtin.service:
        name: catalogue
        state: started
    - name: Copying mongo.repo file
      ansible.builtin.copy:
        src: /home/centos/Projectwork/Ansible/mongo.repo
        dest: /etc/yum.repos.d/mongo.repo
        
    - name: Install mongodb client
      ansible.builtin.dnf:
         name: mongodb-org-shell
         state: latest
    - name: Load schema
      ansible.builtin.shell: mongo --host mongodb.dineshdevops.online </app/schema/catalogue.js
