- name: Installing and configuring payment service
  hosts: payment
  become: yes
  tasks: 
    - name: Installing python 
      ansible.builtin.dnf: 
        name: 
          - python36
          - gcc
          - python3-devel
        state: latest
    - name: Adding user robosop
      ansible.builtin.user: roboshop
    - name: "Creating /app directory"
      ansible.builtin.file:
        path: /app
        state: directory
    - name: Downloading application code
      ansible.builtin.get_url: 
         url: https://roboshop-builds.s3.amazonaws.com/payment.zip
         dest: /tmp/payment.zip
    - name: Extrarting application code
      ansible.builtin.unarchive:
        src: /tmp/payment.zip
        dest: /app
        remote_src: yes
    - name: Installing dependencies
      ansible.builtin.shell: pip3.6 install -r requirements.txt
      args:
       chdir: /app
    - name: Copying payment.service file
      ansible.builtin.file:
        src: /home/centos/Projectwork/Ansible/payment.service
        dest: /etc/systemd/system/payment.service
    - name: Reloading systemd service
      ansible.builtin.systemd_service: 
         daemon_reload: true
    - name: Enabling payment service 
      ansible.builtin.service:
         name: payment
         enabled: yes
    - name: Starting payment service
      ansible.builtin.service:
         name: payment
         state: started