- name: Installing and configuring shipping service
  hosts: shipping
  become: yes
  tasks: 
    - name: Installing maven
      ansible.builtin.dnf: 
        name: maven
        state: latest
    - name: Adding user robosop
      ansible.builtin.user: 
       name: roboshop
    - name: "Creating /app directory"
      ansible.builtin.file:
        path: /app
        state: directory
    - name: Downloading application code
      ansible.builtin.get_url: 
         url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
         dest: /tmp/shipping.zip
    - name: Extrarting application code
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes
    - name: Installing dependencies
      ansible.builtin.shell: mvn clean package ; mv target/shipping-1.0.jar shipping.jar
      args:
       chdir: /app
    - name: Copying shipping.service file
      ansible.builtin.file:
        src: /home/centos/Projectwork/Ansible/shipping.service
        dest: /etc/systemd/system/shipping.service
    - name: Reloading systemd service
      ansible.builtin.systemd_service: 
         daemon_reload: true
    - name: Enabling shipping service 
      ansible.builtin.service:
         name: shipping
         enabled: yes
    - name: Starting shipping service
      ansible.builtin.service:
         name: shipping
         state: started
    - name: Installing mysql
      ansible.builtin.dnf:
         name: mysql
         state: latest 
    - name: Loading schema
      ansible.builtin.shell: mysql -h mysql.dineshdevops.online -uroot -pRoboShop@1 < /app/schema/shipping.sql 
    - name: restarting shipping service
      ansible.builtin.service:
       name: shipping
       state: restarted

